### ISSUE TITLE
Request the ability to add a segment that is _only_ a label (no date or time)

### ISSUE THREAD

**Issue by mamefan1945** [arpadbarta/Time#10]
I would like the ability to add a segment that contains only arbitrary, user specified text.  This would be similar to the Prefix/Suffix but would have no time or date component.  It should have all the same options as existing segments but should not require a time or date. 

Perhaps in the "Format" dropdown there could be a "Text Only" option.

**Comment by arpadbarta** [comment]
"It should have all the same options as existing segments" would mean that you would like to have the "Prefix/Suffix" as well?
Just curious about the use case, how would you use this? Would it be for spacing?

**Comment by 42formvar** [comment]
Hi.
This could be a useful feature for setting reminders like you might have on a "Dementia Clock".  
A hotkey to toggle fullscreen and another to lock access might be useful too.
