### ISSUE TITLE
Make display on one line only

### ISSUE THREAD

**Issue by l2fl2f** [arpadbarta/Time#12]
Dear,

Could you do an option to put the whole information on the same line ? (hour day date)

Regards

**Comment by arpadbarta** [comment]
Hi there,
You can already do it by using a custom format. It allows you to put any part of the date time in what ever order you wish.
![image](https://github.com/arpadbarta/Time/assets/6329203/b31a5243-ef4a-483f-aa58-b593cd86d3d7)
The "Learn more about formatting" button opens the complete list of formatters.
