### ISSUE TITLE
The UTC-04:00 time zone "Atlantic Time (Canada) (Atlantic Standard Time) is wrong

### ISSUE THREAD

**Issue by cognato-net** [arpadbarta/Time#13]
Hi! I absolutely LOVE your program. Thank you so much!!!!

Running on:
Windows 10 Pro N
version 22H2
OS build 19045.4412

Date & Time installed from MS Store.
Version 2.3.0.0

The Time Zone labelled "UTC-04:00 time zone "Atlantic Time (Canada) (Atlantic Standard Time)" is giving me the incorrect time. It's off by +1 hour. None of the other UTC-4 time zones have this problem.

Atlantic Standard Time:
![image](https://github.com/arpadbarta/Time/assets/130794609/d4260a84-b1cd-4a5d-ba28-10ecbb23cd0d)

Any other UTC-4 time zone:
![image](https://github.com/arpadbarta/Time/assets/130794609/7e19bae3-3f7f-4346-81fb-731c200a48c4)

Googling "current time in atlantic standard time":
![image](https://github.com/arpadbarta/Time/assets/130794609/0e9e988c-220b-498d-a9f6-6b9520a5c524)

**Comment by arpadbarta** [comment]
Hi there,
Thanks a lot for your feedback.
These labels are being surfaced from the system time zones, it seems that there is a bug in them.
If you select the same label as the one that you searched for `Atlantic Standard Time` they do much even if the label indicates that it is a UTC-4:
![image](https://github.com/arpadbarta/Time/assets/6329203/1edd0bfc-cac3-492a-8a74-17cfa71b5a33)

I am not sure if I can do a lot about, but I hope this information helps.
