### ISSUE TITLE
Feature Suggestion: Complete transparency, remove arrow.

### ISSUE THREAD

**Issue by MintScot** [arpadbarta/Time#17]
I really like this app, I just have one wee annoyance - I show the date and time with a transparent background. Is there a way to remove that annoying little graphic at the bottom right-hand corner? It shows up like a little arrow on my desktop.

I guarantee you that there's a coffee in it for you, if you could fix this otherwise excellent app.

MintScot

**Comment by arpadbarta** [comment]
Hi there,
If we are talking about this:
![image](https://github.com/user-attachments/assets/93715621-fba8-45cc-9fb1-4cc63320e3a2)

Than you can just disable resize and it disapears:
![image](https://github.com/user-attachments/assets/35f95f75-303a-4bfd-ab08-c19e200993a9)

Is this that you were after?

**Comment by MintScot** [comment]
Thank you! This will stop me shifting the clock all over the screen, changing its postion and size, cracking my partner up. The app is perfect. As promised, coffees on their way. Enjoy.

Wishart
