### ISSUE TITLE
Widget still appears when alt + tab

### ISSUE THREAD

**Issue by abdallah-py** [arpadbarta/Time#18]
I disabled "show window in taskbar option" so it doesn't appear in taskbar anymore, but when I move to a new window with alt + tab shortcut It still appears and makes window transition a bit bothersome (Windows 11)

![{1A8CCC38-8F11-4593-B373-9AF7A75929BA}](https://github.com/user-attachments/assets/76d0e2a9-41d7-466c-a7e2-0f98c5ce55ad)

![{68D1D8D4-12C6-444C-8ECD-D7A515B13B13}](https://github.com/user-attachments/assets/669f73f0-eb47-4964-a964-63ef62a6811e)

![{9D234783-1A99-4904-AF7A-E86D307D4D5D}](https://github.com/user-attachments/assets/147ff250-405f-49bf-80e6-1cde4b53396a)

**Comment by arpadbarta** [comment]
Hi there,
When you navigate in between your windows with Alt + Tab, windows will show you all of the windows that you have on your screen.
As far as I am aware there is no way to opt out of that list, unless you close the window.
