### ISSUE TITLE
I would like to snap the clock to the corner or center of the window.

### ISSUE THREAD

**Issue by Hackgets** [arpadbarta/Time#3]
It is not impossible to do this with Windows functions, but then the size of the clock would not be flexible.

**Comment by arpadbarta** [comment]
It sounds an interesting feature, although it might be a bit more effort.
I have been doing something similar by disabling resize and move the window into one of the [PowerToys FancyZones](https://github.com/microsoft/PowerToys/wiki#fancyzones), this results in snapping the window into the zones top left corner while keeping its size.
Might be a good alternative for the time being.

**Comment by Hackgets** [comment]
I found Fancyzone more useful than I expected. It is just a bit bad that it can't be applied only to specific apps.
